#!/usr/bin/env bash

# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Entrypoint for the apache/ranger-pdp image. Renders conf/ranger-pdp-site.xml from
# RANGER_PDP_SITE_YAML (default: the image's ranger-pdp-site-defaults.yaml), verifies at least
# one authentication handler is usable, and runs the PDP server in the foreground.

set -euo pipefail

RANGER_PDP_HOME=${RANGER_PDP_HOME:-${RANGER_HOME}/pdp}
RANGER_PDP_CONF_DIR=${RANGER_PDP_CONF_DIR:-${RANGER_PDP_HOME}/conf}
RANGER_PDP_LOG_DIR=${RANGER_PDP_LOG_DIR:-/var/log/ranger/pdp}
RANGER_PDP_SITE_YAML=${RANGER_PDP_SITE_YAML:-${RANGER_SCRIPTS}/ranger-pdp-site-defaults.yaml}

PDP_SITE_XML=${RANGER_PDP_CONF_DIR}/ranger-pdp-site.xml
PDP_LOGBACK_XML=${RANGER_PDP_CONF_DIR}/logback.xml

# must match GENERATED_MARKER in render-pdp-site.py
GENERATED_MARKER='generated by ranger-pdp.sh from YAML'

export RANGER_PDP_CONF_DIR RANGER_PDP_LOG_DIR

log()  { echo "ranger-pdp: $*"; }
warn() { echo "ranger-pdp: WARN: $*" >&2; }
die()  { echo "ranger-pdp: ERROR: $*" >&2; exit 1; }

lower() { printf '%s' "${1-}" | tr '[:upper:]' '[:lower:]'; }

is_true() { [ "$(lower "${1-}")" = "true" ]; }

trim() { printf '%s' "${1-}" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//'; }

xml_value() {
    xmlstarlet sel -t -v "/configuration/property[name='$1']/value" -n "${PDP_SITE_XML}" 2>/dev/null | head -1
}

# ranger-pdp ships an empty conf/; seed logback from conf.dist unless one is mounted
seed_conf_dir() {
    mkdir -p "${RANGER_PDP_CONF_DIR}" "${RANGER_PDP_LOG_DIR}"

    if [ ! -f "${PDP_LOGBACK_XML}" ] && ! cp "${RANGER_PDP_HOME}/conf.dist/logback.xml" "${PDP_LOGBACK_XML}" 2>/dev/null; then
        warn "unable to seed ${PDP_LOGBACK_XML}; logback will fall back to its own defaults"
    fi
}

# a file we rendered on a previous start is regenerated, so edits to the YAML take effect on restart
is_user_site_xml() {
    [ -f "${PDP_SITE_XML}" ] && ! grep -q "${GENERATED_MARKER}" "${PDP_SITE_XML}"
}

create_cache_dir() {
    local cache_dir

    cache_dir=$(xml_value ranger.authz.default.policy.cache.dir)

    if [ -n "${cache_dir}" ] && ! mkdir -p "${cache_dir}" 2>/dev/null; then
        warn "unable to create policy cache dir ${cache_dir}; mount it as a writable volume"
    fi
}

# mirrors RangerPdpAuthNFilter.createHandler(): a handler counts only when listed in
# ranger.pdp.authn.types, enabled, and configured. No usable handler => PDP fails to start.
verify_authn() {
    local types usable=() type

    types=$(xml_value ranger.pdp.authn.types)
    types=${types:-header,jwt,kerberos}

    while IFS= read -r type; do
        type=$(trim "$(lower "${type}")")

        case "${type}" in
            header)
                if is_true "$(xml_value ranger.pdp.authn.header.enabled)" &&
                   { [ -n "$(xml_value ranger.pdp.authn.header.username)" ] ||
                     [ -n "$(xml_value ranger.pdp.authn.header.spiffe)" ]; }; then
                    usable+=(header)
                fi
                ;;
            jwt)
                if is_true "$(xml_value ranger.pdp.authn.jwt.enabled)"; then
                    usable+=(jwt)
                fi
                ;;
            kerberos)
                if is_true "$(xml_value ranger.pdp.authn.kerberos.enabled)"; then
                    usable+=(kerberos)
                fi
                ;;
            '') ;;
            *) warn "unknown authentication type '${type}' in ranger.pdp.authn.types" ;;
        esac
    done < <(printf '%s\n' "${types}" | tr ',' '\n')

    if [ ${#usable[@]} -eq 0 ]; then
        die "no usable authentication handler in ${PDP_SITE_XML}; the PDP will not start. Enable header authn by setting ranger.pdp.authn.types to include 'header', ranger.pdp.authn.header.enabled=true and ranger.pdp.authn.header.username (or .spiffe)"
    fi

    log "authentication handlers: ${usable[*]}"
}

seed_conf_dir

if is_user_site_xml; then
    log "using mounted ${PDP_SITE_XML}; YAML and environment variables are ignored"
else
    /usr/bin/python3 "${RANGER_SCRIPTS}/render-pdp-site.py" \
        --input  "${RANGER_PDP_SITE_YAML}" \
        --output "${PDP_SITE_XML}" || die "failed to render ${PDP_SITE_XML}"
fi

verify_authn
create_cache_dir

admin_url=$(xml_value ranger.authz.default.policy.rest.url)

if [ -z "${admin_url}" ]; then
    warn "ranger.authz.default.policy.rest.url is not set; the PDP will use its built-in default Ranger Admin URL"
fi

if [ -z "$(xml_value ranger.authz.default.policy.rest.client.password)" ]; then
    warn "no Ranger Admin password configured; policy download from ${admin_url:-Ranger Admin} will likely fail"
fi

pdp_port=$(xml_value ranger.pdp.port)

log "starting Ranger PDP on port ${pdp_port:-6500}"

cd "${RANGER_PDP_HOME}" || die "${RANGER_PDP_HOME} not found"

exec ./ranger-pdp-services.sh run
