#!/usr/bin/python3

# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Renders ranger-pdp-site.xml from a YAML file of property names and values, expanding
# ${VAR} / ${VAR:-default} references from the environment.

import argparse
import os
import re
import sys

from xml.sax.saxutils import escape

import yaml

GENERATED_MARKER = 'generated by ranger-pdp.sh from YAML'

DEFAULT_HEADER_USERNAME = 'X-Forwarded-User'

ENV_REF = re.compile(r'\$\$|\$\{([A-Za-z_][A-Za-z0-9_]*)(?::-([^}]*))?\}')


def log(msg):
    print(f'ranger-pdp: {msg}', file=sys.stderr)


def die(msg):
    log(f'ERROR: {msg}')
    sys.exit(1)


def load_yaml(path):
    try:
        with open(path) as f:
            data = yaml.safe_load(f)
    except (OSError, yaml.YAMLError) as e:
        die(f'unable to read {path}: {e}')

    if data is None:
        return {}

    if not isinstance(data, dict):
        die(f'{path}: expected a mapping of property name to value')

    for name, value in data.items():
        if not isinstance(name, str):
            die(f'{path}: property name {name!r} must be a string')

        if isinstance(value, dict):
            die(f'{path}: {name}: nested mappings are not supported; use the full property name as the key')

    return data


def expand_env(value):
    # $$ escapes a literal $; like bash, ${VAR:-default} also applies the default when VAR is empty
    def replace(m):
        if m.group(0) == '$$':
            return '$'

        env_value = os.environ.get(m.group(1), '')

        return env_value if env_value or m.group(2) is None else m.group(2)

    return ENV_REF.sub(replace, value)


def to_property_value(value):
    if value is None:
        return None

    if isinstance(value, bool):
        return 'true' if value else 'false'

    if isinstance(value, list):
        return ','.join(v for v in (to_property_value(item) for item in value) if v)

    return expand_env(str(value)).strip()


def enforce_header_authn(props):
    # the PDP refuses to start without a usable authn handler; header authn is this image's baseline
    # an absent key is expected in a user-supplied YAML; only a conflicting value deserves a warning
    header_enabled = props.get('ranger.pdp.authn.header.enabled')

    if header_enabled is None:
        log('header authn is required by this image; setting ranger.pdp.authn.header.enabled=true')
    elif header_enabled.lower() != 'true':
        log(f"WARN: ranger.pdp.authn.header.enabled was '{header_enabled}'; enabling it since this image requires header authn")

    props['ranger.pdp.authn.header.enabled'] = 'true'

    if not props.get('ranger.pdp.authn.header.username') and not props.get('ranger.pdp.authn.header.spiffe'):
        log(f'no header authn header name given; using ranger.pdp.authn.header.username={DEFAULT_HEADER_USERNAME}')

        props['ranger.pdp.authn.header.username'] = DEFAULT_HEADER_USERNAME

    configured_types = props.get('ranger.pdp.authn.types')
    types            = []

    for authn_type in (configured_types or '').split(','):
        authn_type = authn_type.strip().lower()

        if authn_type and authn_type not in types:
            types.append(authn_type)

    if 'header' not in types:
        if configured_types is None:
            log('setting ranger.pdp.authn.types=header')
        else:
            log(f"WARN: ranger.pdp.authn.types '{configured_types}' did not include 'header'; adding it since this image requires header authn")

        types.insert(0, 'header')

    props['ranger.pdp.authn.types'] = ','.join(types)


def write_site_xml(props, path):
    lines = [
        '<?xml version="1.0" encoding="UTF-8"?>',
        f'<!-- {GENERATED_MARKER}; regenerated on every start. Mount your own file to take over -->',
        '<configuration>',
    ]

    for name, value in props.items():
        lines += [
            '  <property>',
            f'    <name>{escape(name)}</name>',
            f'    <value>{escape(value)}</value>',
            '  </property>',
        ]

    lines.append('</configuration>')

    with open(path, 'w') as f:
        f.write('\n'.join(lines) + '\n')


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--input', required=True, help='YAML file of ranger-pdp-site.xml properties')
    parser.add_argument('--output', required=True, help='ranger-pdp-site.xml to write')
    args = parser.parse_args()

    log(f'rendering from {args.input}')

    props = {}

    for name, value in load_yaml(args.input).items():
        value = to_property_value(value)

        if value:
            props[name] = value

    enforce_header_authn(props)
    write_site_xml(props, args.output)

    log(f'generated {args.output}')


if __name__ == '__main__':
    main()
